### ISSUE TITLE
Fails on Windows 10

### ISSUE THREAD

**Issue by SkyLined** [arvydas/blinkstick-node#25]
I am using blinkstick from npm as a dependency in my project and it does not work. So, I did a checkout from github and it simply does not work either. I am using the latest x64 version of Windows 10 and I tested with the 32-bit and 64-bit version of node.

```
P:\dev\node\blinkstick-node>ver

Microsoft Windows [Version 10.0.10240]

P:\dev\node\blinkstick-node>node -v
v7.3.0
P:\dev\node\blinkstick-node>node_x86 blinkstick.js
module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: %1 is not a valid Win32 application.
\\?\P:\dev\node\blinkstick-node\platform\windows\HID.node
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (P:\dev\node\blinkstick-node\blinkstick.js:16:9)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

P:\dev\node\blinkstick-node>node_x64 blinkstick.js
module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: %1 is not a valid Win32 application.
\\?\P:\dev\node\blinkstick-node\platform\windows\HID.node
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (P:\dev\node\blinkstick-node\blinkstick.js:16:9)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

**Comment by SkyLined** [comment]
FYI: The "node-hid" branch works for me.

**Comment by dcerisano** [comment]
For others with the same problem on Windows 10:
```
npm install https://github.com/arvydas/blinkstick-node.git#node-hid
npm update
```
