### ISSUE TITLE
LIBUSB_ERROR_ACCESS

### ISSUE THREAD

**Issue by troywweber7** [arvydas/blinkstick-node#28]
Any ideas why this is occurring? I just spent $40 on this product trusting that the libraries would work =|

Specs:
- Ubuntu 17.04
- Node 7.10.0
- NPM 4.2.0

I installed the required libraries for npm installation:

```bash
$ sudo aptitude install libusb-dev libudev-dev
```

I npm-installed `blinkstick` locally in a folder:

```bash
$ mkdir experiments && cd experiments
$ npm i blinkstick
```

Then I jumped into the node-interpreter and got this error:

```bash
$ node
> blinkstick = require('blinkstick')
{ findFirst: [Function: findFirst],
  findAll: [Function: findAll],
  findAllSerials: [Function: findAllSerials],
  findBySerial: [Function: findBySerial] }
> blinkstick.findFirst()
Error: LIBUSB_ERROR_ACCESS
    at Device.usb.Device.open (/home/troyw/code-local/experiments/blinkstick/node_modules/usb/usb.js:33:7)
    at new BlinkStick (/home/troyw/code-local/experiments/blinkstick/node_modules/blinkstick/blinkstick.js:201:20)
    at Object.findFirst (/home/troyw/code-local/experiments/blinkstick/node_modules/blinkstick/blinkstick.js:1427:32)
    at repl:1:12
    at ContextifyScript.Script.runInThisContext (vm.js:23:33)
    at REPLServer.defaultEval (repl.js:339:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.onLine (repl.js:536:10)
    at emitOne (events.js:101:20)
> blinkstick.findAll()
Error: LIBUSB_ERROR_ACCESS
    at Device.usb.Device.open (/home/troyw/code-local/experiments/blinkstick/node_modules/usb/usb.js:33:7)
    at new BlinkStick (/home/troyw/code-local/experiments/blinkstick/node_modules/blinkstick/blinkstick.js:201:20)
    at findBlinkSticks (/home/troyw/code-local/experiments/blinkstick/node_modules/blinkstick/blinkstick.js:1284:29)
    at Object.findAll (/home/troyw/code-local/experiments/blinkstick/node_modules/blinkstick/blinkstick.js:1446:16)
    at repl:1:12
    at ContextifyScript.Script.runInThisContext (vm.js:23:33)
    at REPLServer.defaultEval (repl.js:339:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.onLine (repl.js:536:10)
> blinkstick.findAllSerials()
Error: LIBUSB_ERROR_ACCESS
    at Device.usb.Device.open (/home/troyw/code-local/experiments/blinkstick/node_modules/usb/usb.js:33:7)
    at new BlinkStick (/home/troyw/code-local/experiments/blinkstick/node_modules/blinkstick/blinkstick.js:201:20)
    at findBlinkSticks (/home/troyw/code-local/experiments/blinkstick/node_modules/blinkstick/blinkstick.js:1284:29)
    at Object.findAllSerials (/home/troyw/code-local/experiments/blinkstick/node_modules/blinkstick/blinkstick.js:1463:23)
    at repl:1:12
    at ContextifyScript.Script.runInThisContext (vm.js:23:33)
    at REPLServer.defaultEval (repl.js:339:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.onLine (repl.js:536:10)
> blinkstick.findBySerial()
Error: LIBUSB_ERROR_ACCESS
    at Device.usb.Device.open (/home/troyw/code-local/experiments/blinkstick/node_modules/usb/usb.js:33:7)
    at new BlinkStick (/home/troyw/code-local/experiments/blinkstick/node_modules/blinkstick/blinkstick.js:201:20)
    at findBlinkSticks (/home/troyw/code-local/experiments/blinkstick/node_modules/blinkstick/blinkstick.js:1284:29)
    at Object.findBySerial (/home/troyw/code-local/experiments/blinkstick/node_modules/blinkstick/blinkstick.js:1496:23)
    at repl:1:12
    at ContextifyScript.Script.runInThisContext (vm.js:23:33)
    at REPLServer.defaultEval (repl.js:339:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.onLine (repl.js:536:10)
```

**Comment by troywweber7** [comment]
Ha. Says solution in [README](https://github.com/arvydas/blinkstick-node#user-content-permission-problems).

And I thought that I had thoroughly read the README already... -.-
